# Generated by Django 3.1.5 on 2021-01-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Unique short readable label', max_length=4000, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descriptive notes')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date created (automatically recorded)')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='Date last modified (automatically recorded)')),
                ('namespace', models.URLField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'authorities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloseMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date created (automatically recorded)')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='Date last modified (automatically recorded)')),
                ('identifier', models.URLField(help_text='URI for this entity in this authority.')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_matches', to='authority.authority')),
            ],
            options={
                'verbose_name_plural': 'close matches',
            },
        ),
    ]
