# Generated by Django 3.1.5 on 2021-01-25 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authority', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date created (automatically recorded)')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='Date last modified (automatically recorded)')),
                ('pref_label', models.CharField(blank=True, db_index=True, default='', max_length=5000)),
                ('user_created', models.ForeignKey(editable=False, help_text='Created by user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitys_created', to=settings.AUTH_USER_MODEL)),
                ('user_last_modified', models.ForeignKey(editable=False, help_text='Last modified by user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitys_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.entity')),
                ('birth_edtf', models.CharField(blank=True, default='', max_length=1000, verbose_name='Birth date expressed in EDTF')),
                ('birth_early', models.DateField(blank=True, null=True)),
                ('birth_late', models.DateField(blank=True, null=True)),
                ('death_edtf', models.CharField(blank=True, default='', max_length=1000, verbose_name='Death date expressed in EDTF')),
                ('death_early', models.DateField(blank=True, null=True)),
                ('death_late', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
            bases=('entity.entity',),
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.entity')),
                ('broader', models.ManyToManyField(related_name='narrower_items', to='entity.Concept')),
                ('narrower', models.ManyToManyField(related_name='broader_items', to='entity.Concept')),
            ],
            bases=('entity.entity',),
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text='Short readable label', max_length=4000)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date created (automatically recorded)')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='Date last modified (automatically recorded)')),
                ('language', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('authority', models.ForeignKey(blank=True, help_text='Authority that uses this name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names_used', to='authority.authority')),
                ('user_created', models.ForeignKey(editable=False, help_text='Created by user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='names_created', to=settings.AUTH_USER_MODEL)),
                ('user_last_modified', models.ForeignKey(editable=False, help_text='Last modified by user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='names_modified', to=settings.AUTH_USER_MODEL)),
                ('name_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_labels', to='entity.person')),
            ],
            options={
                'unique_together': {('label', 'name_of', 'authority')},
            },
        ),
    ]
